apiVersion: apps/v1
kind: Deployment

metadata:
  name: finops-agent
  namespace: finops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: finops-agent

  template:
    metadata:
      labels:
        app: finops-agent

    spec:
      serviceAccountName: finops-agent

      containers:
        - name: finops-agent

          image: ghcr.io/moushmi-grace/autonomous-finops-agent/finops-agent:latest

          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: finops-agent-env

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"