apiVersion: v1
kind: ServiceAccount
metadata:
  name: finops-agent
  namespace: finops

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finops
  name: finops-agent-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]

- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: finops-agent-rolebinding
  namespace: finops
subjects:
- kind: ServiceAccount
  name: finops-agent
  namespace: finops
roleRef:
  kind: Role
  name: finops-agent-role
  apiGroup: rbac.authorization.k8s.io
