apiVersion: v1
kind: Secret
metadata:
  name: finops-agent-secret
  namespace: finops
type: Opaque
stringData:

  PROMETHEUS_URL: http://prometheus-server.monitoring.svc.cluster.local:9090

  K8S_NAMESPACE: finops

  EKS_CLUSTER_NAME: finops-cluster